### ISSUE TITLE
Mac CTranslate2 - cuda error

### ISSUE THREAD

**Issue by bilbofroggins** [Evan-Wildenhain/CTRL-F-VIDEO#1]
Seems like you might not support mac (since it wants to use cuda) but this is what I see on mac M2:

pythons $ python3 app.py
...
  File ".../CTRL-F-VIDEO-master/pythons/app.py", line 13, in <module>
    model_whisper = WhisperModel(model_size, device="cuda", compute_type="float16")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../CTRL-F-VIDEO-master/pythons/venv/lib/python3.12/site-packages/faster_whisper/transcribe.py", line 133, in __init__
    self.model = ctranslate2.models.Whisper(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: This CTranslate2 package was not compiled with CUDA support

**Comment by Evan-Wildenhain** [comment]
Added
<pre>
if torch.backends.mps.is_available():
    DEVICE = torch.device("mps")
elif torch.cuda.is_available():
    DEVICE = torch.device("cuda")
else:
    DEVICE = torch.device("cpu")
model_size = "medium"
model_whisper = WhisperModel(model_size, device=str(DEVICE), compute_type="float16")
</pre>
at the start, try now and it should work, but i havent worked with a mac before so if you run into any more errors let me know
